name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t  angelad25/my-dear-portfolio .

      - name: Push image
        run: |
        docker login -u angelad25 -p ${{secrets.REGISTRY_PASS}}
        docker push angelad25/my-dear-portfolio